# Generated by Django 5.0.2 on 2025-02-23 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('risk_tolerance', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('investment_type', models.CharField(choices=[('SHORT_TERM', 'Short Term'), ('MID_TERM', 'Mid Term'), ('LONG_TERM', 'Long Term')], default='LONG_TERM', max_length=15)),
                ('investment_reason', models.CharField(choices=[('WEALTH_GROWTH', 'Wealth Growth'), ('EDUCATION', 'Education'), ('RETIREMENT', 'Retirement'), ('ESTATE', 'Estate Planning')], default='WEALTH_GROWTH', max_length=20)),
                ('income_range', models.CharField(choices=[('UNDER_2_LPA', 'Under 2 LPA'), ('2_TO_5_LPA', '2-5 LPA'), ('5_TO_10_LPA', '5-10 LPA'), ('10_TO_20_LPA', '10-20 LPA'), ('20_LPA_PLUS', '20 LPA+')], default='UNDER_2_LPA', max_length=20)),
                ('investment_experience', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'stock_symbol'], name='api_portfol_user_id_c70bce_idx'), models.Index(fields=['stock_symbol', '-purchase_date'], name='api_portfol_stock_s_8c0d80_idx')],
                'unique_together': {('user', 'stock_symbol')},
            },
        ),
    ]
