# Generated by Django 5.0 on 2025-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment_horizon',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment_style',
            field=models.CharField(choices=[('Conservative', 'Conservative'), ('Balanced Growth', 'Balanced Growth'), ('Aggressive Growth', 'Aggressive Growth')], default='Conservative', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_sectors',
            field=models.JSONField(default=list),
        ),
    ]
