# Generated by Django 5.0 on 2025-02-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_sectors',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('REAL_ESTATE', 'Real Estate'), ('WEALTH_GROWTH', 'Wealth Growth')], default='EDUCATION', max_length=20),
        ),
    ]
