# Generated by Django 4.2 on 2025-02-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_portfolio_total_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
