# Generated by Django 5.1.6 on 2025-02-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_portfolio_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('alert_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('percent_change', 'Percent Change'), ('volume_above', 'Volume Above')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('notification_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'stock_symbol', 'is_active'], name='api_stockal_user_id_853242_idx')],
            },
        ),
    ]
