# Generated by Django 5.1.6 on 2025-02-20 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('provider', models.CharField(choices=[('GEMINI', 'Google Gemini'), ('GPT', 'OpenAI GPT'), ('CLAUDE', 'Anthropic Claude')], max_length=10)),
                ('response', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='user',
        ),
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIRecommendation',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='StockAlert',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['user', 'provider'], name='api_aianaly_user_id_339987_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['created_at'], name='api_aianaly_created_f7e455_idx'),
        ),
    ]
